# Generated by Django 5.1.6 on 2025-04-14 09:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_auto_create_groups"),
        ("rooms", "0002_department_room_department_floor_alter_room_floor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="department",
        ),
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "permissions": [
                    ("view_all_users", "Can view all users"),
                    ("moderate_user", "Can moderate users"),
                    ("promote_to_coordinator", "Can promote to Coordinator"),
                    ("promote_to_admin", "Can promote to Admin"),
                    ("promote_to_super_admin", "Can promote to SuperAdmin"),
                    ("demote_to_user", "Can demote to User"),
                    ("demote_to_coordinator", "Can demote to Coordinator"),
                    ("demote_to_admin", "Can demote to Admin"),
                ]
            },
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="is_faculty",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="user_category",
        ),
        migrations.AddField(
            model_name="customuser",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="customuser",
            name="managed_departments",
            field=models.ManyToManyField(blank=True, to="rooms.department"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="managed_floors",
            field=models.ManyToManyField(blank=True, to="rooms.floor"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name="Department",
        ),
    ]
