# Generated by Django 5.1.8 on 2025-04-30 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_customuser_created_at"),
        ("rooms", "0006_remove_amenity_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="managed_buildings",
            field=models.ManyToManyField(
                blank=True, related_name="managers", to="rooms.building"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
