# Generated by Django 5.1.6 on 2025-04-14 12:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0001_initial"),
        ("rooms", "0003_alter_amenity_options_alter_building_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={
                "permissions": [
                    ("view_own_booking", "Can view own bookings"),
                    ("create_booking", "Can create bookings"),
                    ("modify_own_booking", "Can modify own bookings"),
                    ("cancel_own_booking", "Can cancel own bookings"),
                    ("view_all_bookings", "Can view all bookings"),
                    (
                        "view_floor_dept_bookings",
                        "Can view bookings for floor or department",
                    ),
                    ("approve_booking", "Can approve bookings"),
                    ("reject_booking", "Can reject bookings"),
                    ("override_booking", "Can override bookings"),
                ]
            },
        ),
        migrations.AddField(
            model_name="booking",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="booking",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="rooms.room",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["room", "start_time", "end_time"],
                name="bookings_bo_room_id_40c02a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["user"], name="bookings_bo_user_id_0e7f91_idx"),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["status"], name="bookings_bo_status_233e96_idx"),
        ),
    ]
