# Generated by Django 5.1.6 on 2025-04-18 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_alter_booking_options_booking_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("calendar_id", models.CharField(max_length=255)),
                ("event_id", models.CharField(max_length=255)),
                ("html_link", models.URLField(blank=True, max_length=500, null=True)),
                ("synced_at", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_event",
                        to="bookings.booking",
                    ),
                ),
            ],
        ),
    ]
