# Generated by Django 5.1.6 on 2025-04-19 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_calendarevent"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CalendarEvent",
        ),
    ]
