# Generated by Django 5.1.8 on 2025-05-01 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_calendarevent"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CalendarEvent",
        ),
    ]
