# Generated by Django 5.1.8 on 2025-05-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0004_delete_calendarevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
