# Generated by Django 5.1.6 on 2025-04-14 12:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0002_department_room_department_floor_alter_room_floor"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="amenity",
            options={"permissions": [("manage_amenities", "Can manage amenities (add/delete)")]},
        ),
        migrations.AlterModelOptions(
            name="building",
            options={"permissions": [("manage_buildings", "Can manage buildings (add/delete)")]},
        ),
        migrations.AlterModelOptions(
            name="department",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="floor",
            options={"ordering": ["number"]},
        ),
        migrations.AlterModelOptions(
            name="room",
            options={
                "permissions": [
                    ("view_rooms", "Can view all rooms"),
                    ("manage_rooms", "Can manage rooms (add/modify/delete)"),
                ]
            },
        ),
        migrations.RemoveField(
            model_name="room",
            name="department",
        ),
        migrations.RemoveField(
            model_name="room",
            name="description",
        ),
        migrations.AddField(
            model_name="building",
            name="location",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="department",
            name="code",
            field=models.CharField(
                blank=True, help_text="Department code (e.g., CS, EE)", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="room",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="room",
            name="departments",
            field=models.ManyToManyField(
                blank=True,
                help_text="Departments that have access to this room",
                related_name="rooms",
                to="rooms.department",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="amenity",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="building",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="department",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="floor",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Optional display name (e.g., 'Mezzanine', 'Ground Floor')",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="floor",
            name="number",
            field=models.IntegerField(help_text="Floor number (e.g., 1, 2, 3, or -1 for basement)"),
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(fields=["building", "floor"], name="rooms_room_buildin_d6dce3_idx"),
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(fields=["available"], name="rooms_room_availab_3eac53_idx"),
        ),
    ]
