# Generated by Django 5.1.6 on 2025-04-14 23:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0004_amenity_icon_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="amenity",
            name="icon_url",
        ),
        migrations.AddField(
            model_name="amenity",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Upload an icon for this amenity.",
                null=True,
                upload_to="amenity_icons/",
            ),
        ),
    ]
