# Generated by Django 5.1.6 on 2025-04-15 00:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0005_remove_amenity_icon_url_amenity_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="amenity",
            name="image",
        ),
    ]
