# Generated by Django 5.1.8 on 2025-05-02 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0006_remove_amenity_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Whether this room is active and can be booked"
            ),
        ),
    ]
