# Generated by Django 5.1.8 on 2025-05-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0007_room_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Whether this room is available and can be booked",
            ),
        ),
    ]
