# Generated by Django 5.1.6 on 2025-04-14 06:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InstitutePolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Institute Policy", max_length=100)),
                ("description", models.TextField(default="No description provided")),
                ("is_active", models.BooleanField(default=True)),
                ("booking_opening_days", models.PositiveIntegerField(default=30)),
                ("max_booking_duration_hours", models.PositiveIntegerField(default=4)),
                (
                    "min_gap_between_bookings_minutes",
                    models.PositiveIntegerField(default=15),
                ),
                ("working_hours_start", models.TimeField(default="08:00")),
                ("working_hours_end", models.TimeField(default="19:00")),
                ("allow_backdated_bookings", models.BooleanField(default=False)),
                ("enable_auto_approval", models.BooleanField(default=False)),
                ("approval_window_hours", models.PositiveIntegerField(default=48)),
            ],
        ),
    ]
