# Generated by Django 5.1.6 on 2025-04-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="institutepolicy",
            options={
                "permissions": [("manage_institute_policies", "Can manage institute policies")]
            },
        ),
        migrations.RemoveField(
            model_name="institutepolicy",
            name="description",
        ),
        migrations.RemoveField(
            model_name="institutepolicy",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="institutepolicy",
            name="name",
        ),
        migrations.AddField(
            model_name="institutepolicy",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
