# Generated by Django 5.1.8 on 2025-05-02 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0002_alter_institutepolicy_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institutepolicy",
            name="min_gap_between_bookings_minutes",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
