# Generated by Django 5.1.6 on 2025-03-31 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unnamed Room', max_length=100, unique=True)),
                ('description', models.TextField(default='No description provided')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capacity', models.IntegerField(default=10)),
                ('is_available', models.BooleanField(default=True)),
                ('building', models.CharField(default='Lecture Hall Complex', max_length=100)),
                ('amenities', models.JSONField(default=dict)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
